### ISSUE TITLE
Serialisation of ModelRun object to disk

### ISSUE THREAD

**Issue by pbranson** [rom-py/rompy-legacy#166]
I have a usage question, suppose I have constructed a ModelRun and associated config, procedurally in a notebook. Now I want to serialise the configuration to disk to allow round tripping and as a mechanism to 'archive' the rompy parameterisation along with the configured model run.

What is the recommended way to do this?

Currently I have done:
```
run = ModelRun(
    run_id=run_id,
    period=run_time,
    output_dir=output_dir,
    config=config,
)

# Serialise the run to yaml
import yaml
with open(Path(rundir) / 'run_config.yml', 'w') as f:
    yaml.dump(run.dump_inputs_dict(), f, default_flow_style=False)

# Round trip the config
with open(Path(rundir) / 'run_config.yml', 'r') as f:
    content = f.read()
args = yaml.load(content, Loader=yaml.Loader)
model = ModelRun(**args)
```

This works, however the resulting yaml isnt really human readable as the types arent cast into basic datatypes. 
e.g.:
```
config: !!python/object:rompy.schism.config.SCHISMConfig
  __dict__:
    _original_inputs:
      data: &id012 !!python/object:rompy.schism.data.SCHISMData
        __dict__:
          _original_inputs:
            atmos: &id007 !!python/object:rompy.schism.data.SCHISMDataSflux
              __dict__:
                _original_inputs:
                  air_1: &id001 !!python/object:rompy.core.data.DataBlob
                    __dict__:
                      _original_inputs:
                        link: true
                        source: !!python/object/apply:pathlib.PosixPath
...
```

Possibly I am not correctly making use of a pydantic method? Advice appreciated
